services:
    GepurIt\AccessManagerBundle\AccessDecisionManager:
        autowire: true
        arguments:
            $providerKey: 'main'

    GepurIt\AccessManagerBundle\AccessChecker:
        autowire: true

    GepurIt\AccessManagerBundle\EventListener\AccessListener:
        autowire: true
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }
